services:
  linkery-frontend:
    container_name: linkery-frontend
    build: ../linkery-frontend
    volumes:
      - ./proxy:/etc/nginx/conf.d
    ports:
      - 80:80
  linkery-backend:
    container_name: linkery-backend
    build: ../linkery-backend
    env_file: .env
    depends_on: 
      - linkery-database
  linkery-database:
    container_name: linkery-database
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: ${LINKERY_BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${LINKERY_BACKEND_DATABASE_PASSWORD}
      POSTGRES_DB: ${LINKERY_BACKEND_DATABASE_NAME}
    ports:
      - 5432:5432